language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t pilyeooong/backend-test -f ./backend/Dockerfile ./backend

script:
    - docker run -e CI=true pilyeooong/backend-test npm run test

after_success:
    - docker build -t pilyeooong/hotjeju-frontend ./frontend
    - docker build -t pilyeooong/hotjeju-backend ./backend
    - docker build -t pilyeooong/hotjeju-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push pilyeooong/hotjeju-frontend
    - docker push pilyeooong/hotjeju-backend
    - docker push pilyeooong/hotjeju-nginx