language: generic

sudo: required

services:
    - docker

script:
    - echo 'skip tests'

after_success:
    - docker build -t pilyeooong/hotjeju-frontend ./frontend
    - docker build -t pilyeooong/hotjeju-backend ./backend
    - docker build -t pilyeooong/hotjeju-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push pilyeooong/hotjeju-frontend
    - docker push pilyeooong/hotjeju-backend
    - docker push pilyeooong/hotjeju-nginx