version: "3"

networks:
    hotjeju:
        driver: bridge
services:
    mysql:
        networks:
            - hotjeju
        image: mysql
        restart: unless-stopped
        container_name: hotjeju_mysql
        ports:
            - "3306:3306"

    backend:
        networks:
            - hotjeju
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        container_name: hotjeju_backend
        volumes: 
            - /app/node_modules
            - ./backend:/app
        ports:
            - "4000:4000"
        links:
            - mysql
        depends_on:
            - mysql