version: "3"

networks:
    hotjeju:
        driver: bridge
services:
    nginx:
        restart: always
        networks:
            - hotjeju
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3000:80"
    backend:
        networks: 
            - hotjeju
        build:
            dockerfile: Dockerfile
            context: ./backend
        container_name: hotjeju_backend
        volumes: 
            - /app/node_modules
            - ./backend:/app
    frontend:
        networks:
            - hotjeju
        build:
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
    # mysql:
    #     env_file: .env
    #     networks:
    #         - hotjeju
    #     image: mysql
    #     # build: ./mysql
    #     restart: unless-stopped
    #     container_name: hotjeju_mysql
    #     ports:
    #         - "3306:3306"
    #     environment: 
    #         MYSQL_DATABASE: hotjeju
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql